vich_uploader:
    db_driver: orm

    mappings:
        annonces:
            uri_prefix: /image/maison
            upload_destination: '%kernel.project_dir%/public/image/maison'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer